---
fixtures:
  forge_modules:
    apt: puppetlabs/apt
    augeasproviders_apache: puppet/augeasproviders_apache
    epel: puppet/epel
    firewall: puppetlabs/firewall
    httpauth: jamtur01/httpauth
    stdlib: puppetlabs/stdlib
    yumrepo_core: puppetlabs/yumrepo_core
