---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - centos-7
      - ---centos-8
      - debian-9
      - ubuntu-1604
      - ubuntu-1804
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  required:
    ':development':
      - gem: rspec-json_expectations
spec/acceptance/nodesets/centos-8.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2004.yml:
  delete: true
spec/spec_helper.rb:
  spec_overrides:
    - "require 'rspec/json_expectations'"
