---
.github/workflows/ci.yaml:
  unit_excludes:
    puppet: '8'
  acceptance_matrix:
    set:
      - el7
      - el8
      - el9
      - debian-10
      - ubuntu-2004
    puppet:
      - puppet7
      - ---puppet8
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  required:
    ':development':
      - gem: rspec-json_expectations
spec/acceptance/nodesets/debian-11.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2204.yml:
  delete: true
spec/spec_helper.rb:
  spec_overrides:
    - "require 'rspec/json_expectations'"
